Repository jetkvm/kvm, pull requests merged in 2025-02, with the labels that each got.

#27 fix(cloud): only start WS Client if config.CloudToken is set
  cloud.go
  main.go
Labels: enhancement

#86 Remove rounded corners from video stream
  ui/src/components/WebRTCVideo.tsx
Labels: ui

#85 Fix fullscreen video absolute position
  ui/package.json
  ui/src/components/ActionBar.tsx
  ui/src/components/WebRTCVideo.tsx
  ui/vite.config.ts
Labels: enhancement, ui

#34 feat: restore EDID on reboot
  config.go
  jsonrpc.go
  native.go
Labels: enhancement
